import type { Metadata } from "next";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/Sidebar";
import { requireAuth } from "@/lib/session";

export const metadata: Metadata = {
  title: "IntelliVault",
  description: "Generated by create next app",
};

export default async function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Require authentication - redirects to /signin if not authenticated
  const session = await requireAuth();

  return (
    <SidebarProvider>
      <AppSidebar session={session} />
      <main className="w-screen">{children}</main>
    </SidebarProvider>
  );
}
