import type { Metadata } from "next";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/Sidebar";
import { requireAuth } from "@/lib/session";

export const metadata: Metadata = {
  title: "IntelliVault",
  description: "Generated by create next app",
};

export default async function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Require authentication - redirects to /signin if not authenticated
  const session = await requireAuth();

  return (
    <SidebarProvider>
      <AppSidebar session={session} />
      <main className="w-full h-screen overflow-hidden">
        {/*
          Persistent mobile navigation trigger. On phones the sidebar collapses
          into an off-canvas Sheet that defaults closed, so the in-sidebar
          trigger is unreachable. This floating trigger lives outside the Sheet
          (it only needs SidebarProvider context) and is hidden from md: up,
          where the in-sidebar trigger takes over. The content wrapper reserves
          a left gutter on mobile so page headers never sit under it.
        */}
        {/*
          App content canvas.
          On both mobile and desktop, the page takes up the full width/height
          with a flush layout.
        */}
        <div
          className="h-full w-full overflow-hidden p-0"
        >
          {children}
        </div>
      </main>
    </SidebarProvider>
  );
}
